---
- name: Set up Nasir's preffered Fedora Workstation configuration
  hosts: workstation
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    target_group: nasirhm
    target_user: nasirhm
    target_user_name: Nasir Hussain
    user_home_dir: /home/nasirhm

   roles:
     - {role: system/fedora-workstation}
     - {role: system/python}
     - {role: apps/i3wm}
     - {role: apps/thunderbird}
